build:
  image: ruby:2.1.5
  environment:
    - blah=foobar
  commands:
    - export BUILDSTAMP="${CI_COMMIT}-${CI_BUILD_NUMBER}"
    - env | sort
    - bundle install
    - bundle exec rake middleman-build
