name: Build site

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - name: build
      uses: docker://moredip/todo-backend-site:master
      args: build
